name: Tests

on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install pipenv
        run: pip install pipenv
      - name: Install development dependencies
        run: pipenv install --dev
      - name: Run tests
        run: pipenv run test
